AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Clouformation POC

  '
Resources:
  PocPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: cloudformation-poc-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      MfaConfiguration: 'ON'
      AutoVerifiedAttributes:
      - phone_number
      SmsConfiguration:
        ExternalId:
          Fn::Sub: ${AWS::StackName}-external
        SnsCallerArn:
          Fn::GetAtt:
          - SNSRole
          - Arn
      EnabledMfas:
      - SMS_MFA
      - SOFTWARE_TOKEN_MFA
  SNSRole:
    Type: AWS::IAM::Role
    Description: An IAM Role to allow Cognito to send SNS messages
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-cognito-sns-role
      ManagedPolicyArns:
      - Ref: CognitoSNSPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service:
            - cognito-idp.amazonaws.com
    DependsOn:
    - CognitoSNSPolicy
  CognitoSNSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow Amazon Cognito to access SNS
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: sns:publish
          Resource: '*'
